name: Python CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Ckeckout my project 
      - uses: actions/checkout@v3
      - name: Install Python 3.10
      - uses: actions/setup-python@v4
        with: 
          python-version: "3.10"
      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt
      - name: Run application
        run: |
          ubicorn main:app --reload
      - name: Run tests
        run: |
          pythpn -m pytest
